import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "./globals.css";
import SideBarAndTopBarLayout from "@/layout/SideBarAndTopBarLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" expand={true} richColors />
        <SideBarAndTopBarLayout>
          {children}
        </SideBarAndTopBarLayout>
      </body>
    </html>
  );
}
